name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      script:
        description: "Path of the script to publish"
        required: true
        type: choice
        options:
          - iot/tunnel

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
          cache-dependency-path: ${{ github.event.inputs.script }}/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Run tests
        working-directory: ${{ github.event.inputs.script }}
        run: |
          pip install -r requirements-dev.txt
          pip install -e .
          pytest

      - name: Build the package
        run: |
          cd ${{ github.event.inputs.script }}
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ github.event.inputs.script }}/dist
